apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-spring
  namespace: gitops
  labels:
    app: gitops-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-spring
  template:
    metadata:
      labels:
        app: gitops-spring
    spec:
      containers:
        - name: gitops-spring
          image: venkat7010/springboot-devsecops:13
          imagePullPolicy: Always
          ports:
            - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: gitops-spring
  namespace: gitops
spec:
  selector:
    app: gitops-spring
  ports:
    - port: 80
      targetPort: 8090
